@MinimalWeb_HostAddress = https://localhost:7007
@id = 56

GET {{MinimalWeb_HostAddress}}/products
Accept: application/json
###

POST {{MinimalWeb_HostAddress}}/products
Content-Type: application/json

{
  "name":"Test"
}
###

GET {{MinimalWeb_HostAddress}}/products/{{id}}
Accept: application/json
###

PUT {{MinimalWeb_HostAddress}}/products/{{id}}
Content-Type: application/json

{
  "name":"Test2"
}
###

DELETE {{MinimalWeb_HostAddress}}/products/{{id}}

###
