using ProductsReviews.DAL.Entities;

namespace ProductsReviews.DAL.EntityFramework;

public class DbInitializer
{
    public static void Initialize(ProductReviewsContext ctx)
    {
        if (ctx.Database.EnsureCreated())
        {
            Seed(ctx);
        }
    }
    private static void Seed(ProductReviewsContext ctx)
    {
        ctx.ProductGroups!.AddRange(ProductGroups);
        ctx.Products!.AddRange(Products); 
        ctx.Brands!.AddRange(Brands);
        ctx.Reviews!.AddRange(Reviews);
        ctx.SaveChanges();
    }

    private static List<ProductGroup> ProductGroups => new List<ProductGroup> {
            new ProductGroup { Name="Laserprinters", Image="laserprinters.png"},
            new ProductGroup { Name="Laptops en notebooks", Image="laptops_en_notebooks.png"},
            new ProductGroup { Name="Inkjet-printers", Image="inkjet_printers.png"},
            new ProductGroup { Name="MP3-spelers", Image="mp3_spelers.png"},
            new ProductGroup { Name="Beamers en projectoren", Image="beamers_en_projectoren.png"},
            new ProductGroup { Name="Digitale Camera's", Image="digitale_camera_s.png"},
            new ProductGroup { Name="Draadloze routers", Image="draadloze_routers.png"},
            new ProductGroup { Name="Spiegelreflex Camera's", Image="spiegelreflex_camera_s.png"},
            new ProductGroup { Name="Scanners", Image="scanners.png"},
            new ProductGroup { Name="Huistelefoons", Image="huistelefoons.png"},
            new ProductGroup { Name="PC", Image="pc.png"},
            new ProductGroup { Name="Monitors", Image="monitors.png"}
        };
    private static List<Product> Products => new List<Product>{
            new Product { Name="ThinkPad Yoga 260 (Core i5)", Image="lenovo_thinkpad_yoga_260__core_i5_.png", BrandId=1, ProductGroupId=2},
            new Product { Name="KX-TG8090", Image="panasonic_kx_tg8090.png", BrandId=39, ProductGroupId=10},
            new Product { Name="SE745", Image="philips_se745.png", BrandId=29, ProductGroupId=10},
            new Product { Name="KX-TG8061", Image="panasonic_kx_tg8061.png", BrandId=39, ProductGroupId=10},
            new Product { Name="KX-TG8051", Image="panasonic_kx_tg8051.png", BrandId=39, ProductGroupId=10},
            new Product { Name="KX-TG8561", Image="panasonic_kx_tg8561.png", BrandId=39, ProductGroupId=10},
            new Product { Name="KX-PRX150 ", Image="panasonic_kx_prx150_.png", BrandId=39, ProductGroupId=10},
            new Product { Name="KX-PRW120", Image="panasonic_kx_prw120.png", BrandId=39, ProductGroupId=10},
            new Product { Name="KX-PRX120", Image="panasonic_kx_prx120.png", BrandId=39, ProductGroupId=10},
            new Product { Name="KX-TGH220", Image="panasonic_kx_tgh220.png", BrandId=39, ProductGroupId=10},
            new Product { Name="D350A", Image="grundig_d350a.png", BrandId=9, ProductGroupId=10},
            new Product { Name="D4551", Image="philips_d4551.png", BrandId=29, ProductGroupId=10},
            new Product { Name="KX-TGK320 ", Image="panasonic_kx_tgk320_.png", BrandId=39, ProductGroupId=10},
            new Product { Name="SEEN ", Image="grundig_seen_.png", BrandId=9, ProductGroupId=10},
            new Product { Name="EOS 6D", Image="canon_eos_6d.png", BrandId=43, ProductGroupId=8},
            new Product { Name="Alpha SLT-A99V", Image="sony_alpha_slt_a99v.png", BrandId=31, ProductGroupId=8},
            new Product { Name="Boomerang ", Image="aeg_boomerang_.png", BrandId=10, ProductGroupId=10},
            new Product { Name="EOS-1D X", Image="canon_eos_1d_x.png", BrandId=43, ProductGroupId=8},
            new Product { Name="S850A Go ", Image="gigaset_s850a_go_.png", BrandId=11, ProductGroupId=10},
            new Product { Name="SL930A", Image="gigaset_sl930a.png", BrandId=11, ProductGroupId=10},
            new Product { Name="RT-AC3200", Image="asus_rt_ac3200.png", BrandId=32, ProductGroupId=7},
            new Product { Name="RT1900AC ", Image="synology_rt1900ac_.png", BrandId=17, ProductGroupId=7},
            new Product { Name="Butler 5710", Image="topcom_butler_5710.png", BrandId=16, ProductGroupId=10},
            new Product { Name="SL400A", Image="siemens_sl400a.png", BrandId=28, ProductGroupId=10},
            new Product { Name="ePure", Image="swissvoice_epure.png", BrandId=15, ProductGroupId=10},
            new Product { Name="Fritz!Fon MT-F", Image="avm_fritz_fon_mt_f.png", BrandId=13, ProductGroupId=10},
            new Product { Name="Fritz!Fon M2", Image="avm_fritz_fon_m2.png", BrandId=13, ProductGroupId=10},
            new Product { Name="Audioline Surf", Image="audioline_audioline_surf.png", BrandId=12, ProductGroupId=10},
            new Product { Name="A400A", Image="gigaset_a400a.png", BrandId=11, ProductGroupId=10},
            new Product { Name="C610 A", Image="gigaset_c610_a.png", BrandId=11, ProductGroupId=10},
            new Product { Name="E500", Image="gigaset_e500.png", BrandId=11, ProductGroupId=10},
            new Product { Name="A510", Image="gigaset_a510.png", BrandId=11, ProductGroupId=10},
            new Product { Name="SL910A", Image="gigaset_sl910a.png", BrandId=11, ProductGroupId=10},
            new Product { Name="C620A Duo", Image="gigaset_c620a_duo.png", BrandId=11, ProductGroupId=10},
            new Product { Name="E630A", Image="gigaset_e630a.png", BrandId=11, ProductGroupId=10},
            new Product { Name="Dune CL540A", Image="gigaset_dune_cl540a.png", BrandId=11, ProductGroupId=10},
            new Product { Name="D5200", Image="nikon_d5200.png", BrandId=47, ProductGroupId=8},
            new Product { Name="D7100", Image="nikon_d7100.png", BrandId=47, ProductGroupId=8},
            new Product { Name="EOS 100D", Image="canon_eos_100d.png", BrandId=43, ProductGroupId=8},
            new Product { Name="EOS 760D", Image="canon_eos_760d.png", BrandId=43, ProductGroupId=8},
            new Product { Name="D7200", Image="nikon_d7200.png", BrandId=47, ProductGroupId=8},
            new Product { Name="K-S2", Image="pentax_k_s2.png", BrandId=8, ProductGroupId=8},
            new Product { Name="K-3 II", Image="pentax_k_3_ii.png", BrandId=8, ProductGroupId=8},
            new Product { Name="PLED-W800", Image="viewsonic_pled_w800.png", BrandId=7, ProductGroupId=5},
            new Product { Name="PJD7822HDL", Image="", BrandId=7, ProductGroupId=5},
            new Product { Name="PJD5555w", Image="viewsonic_pjd5555w.png", BrandId=7, ProductGroupId=5},
            new Product { Name="Qumi Q5", Image="vivitek_qumi_q5.png", BrandId=6, ProductGroupId=5},
            new Product { Name="GT1080", Image="optoma_gt1080.png", BrandId=5, ProductGroupId=5},
            new Product { Name="HD26", Image="optoma_hd26.png", BrandId=5, ProductGroupId=5},
            new Product { Name="HD36", Image="optoma_hd36.png", BrandId=5, ProductGroupId=5},
            new Product { Name="HD 151 X", Image="optoma_hd_151_x.png", BrandId=5, ProductGroupId=5},
            new Product { Name="EH320UST", Image="optoma_eh320ust.png", BrandId=5, ProductGroupId=5},
            new Product { Name="HD28DSE", Image="optoma_hd28dse.png", BrandId=5, ProductGroupId=5},
            new Product { Name="H6520BD", Image="acer_h6520bd.png", BrandId=37, ProductGroupId=5},
            new Product { Name=" EOS 5Ds", Image="canon__eos_5ds.png", BrandId=43, ProductGroupId=8},
            new Product { Name="EOS 750D", Image="canon_eos_750d.png", BrandId=43, ProductGroupId=8},
            new Product { Name="D5500", Image="nikon_d5500.png", BrandId=47, ProductGroupId=8},
            new Product { Name="EOS 7D Mark II", Image="canon_eos_7d_mark_ii.png", BrandId=43, ProductGroupId=8},
            new Product { Name="EOS 700D", Image="canon_eos_700d.png", BrandId=43, ProductGroupId=8},
            new Product { Name="SLT-A58", Image="sony_slt_a58.png", BrandId=31, ProductGroupId=8},
            new Product { Name="K-50", Image="pentax_k_50.png", BrandId=8, ProductGroupId=8},
            new Product { Name="EOS 70D", Image="canon_eos_70d.png", BrandId=43, ProductGroupId=8},
            new Product { Name="D610", Image="nikon_d610.png", BrandId=47, ProductGroupId=8},
            new Product { Name="D5300", Image="nikon_d5300.png", BrandId=47, ProductGroupId=8},
            new Product { Name="Df", Image="nikon_df.png", BrandId=47, ProductGroupId=8},
            new Product { Name="ModemAC Router FRITZBox 3490 WiF i AC 1750", Image="avm_modemac_router_fritzbox_3490_wif_i_ac_1750.png", BrandId=13, ProductGroupId=7},
            new Product { Name="K-3", Image="pentax_k_3.png", BrandId=8, ProductGroupId=8},
            new Product { Name="EOS 1200D", Image="canon_eos_1200d.png", BrandId=43, ProductGroupId=8},
            new Product { Name="D4S", Image="nikon_d4s.png", BrandId=47, ProductGroupId=8},
            new Product { Name="SLT A 77 II", Image="sony_slt_a_77_ii.png", BrandId=31, ProductGroupId=8},
            new Product { Name="D810", Image="nikon_d810.png", BrandId=47, ProductGroupId=8},
            new Product { Name="645Z", Image="pentax_645z.png", BrandId=8, ProductGroupId=8},
            new Product { Name="D750", Image="nikon_d750.png", BrandId=47, ProductGroupId=8},
            new Product { Name="K-S1", Image="pentax_k_s1.png", BrandId=8, ProductGroupId=8},
            new Product { Name="D3300", Image="nikon_d3300.png", BrandId=47, ProductGroupId=8},
            new Product { Name="VPL-VW1100ES", Image="sony_vpl_vw1100es.png", BrandId=31, ProductGroupId=5},
            new Product { Name="RT-AC87U", Image="asus_rt_ac87u.png", BrandId=32, ProductGroupId=7},
            new Product { Name="FRITZ!Box 7490 ", Image="avm_fritz_box_7490_.png", BrandId=13, ProductGroupId=7},
            new Product { Name="HL-L2300D", Image="brother_hl_l2300d.png", BrandId=50, ProductGroupId=1},
            new Product { Name="Pro M201dw", Image="hp_pro_m201dw.png", BrandId=34, ProductGroupId=1},
            new Product { Name="i-SENSYS LBP6030W", Image="canon_i_sensys_lbp6030w.png", BrandId=43, ProductGroupId=1},
            new Product { Name="I sensys lbp 6230 w", Image="canon_i_sensys_lbp_6230_w.png", BrandId=43, ProductGroupId=1},
            new Product { Name="SP C252SF", Image="", BrandId=41, ProductGroupId=1},
            new Product { Name="LaserJet Color Enterprise M553dn", Image="hp_laserjet_color_enterprise_m553dn.png", BrandId=34, ProductGroupId=1},
            new Product { Name="M553x", Image="hp_m553x.png", BrandId=34, ProductGroupId=1},
            new Product { Name="LaserJet Color Pro M252dw", Image="hp_laserjet_color_pro_m252dw.png", BrandId=34, ProductGroupId=1},
            new Product { Name="E310dw", Image="dell_e310dw.png", BrandId=33, ProductGroupId=1},
            new Product { Name="Gmini XS 100 (4 GB)", Image="archos_gmini_xs_100__4_gb_.png", BrandId=27, ProductGroupId=4},
            new Product { Name="Clip Sport", Image="sandisk_clip_sport.png", BrandId=26, ProductGroupId=4},
            new Product { Name="Plenue 1", Image="cowon_plenue_1.png", BrandId=25, ProductGroupId=4},
            new Product { Name="Plenue M", Image="cowon_plenue_m.png", BrandId=25, ProductGroupId=4},
            new Product { Name="iPod Nano 5G (16GB)", Image="apple_ipod_nano_5g__16gb_.png", BrandId=24, ProductGroupId=4},
            new Product { Name="GoGear Ariaz16GB", Image="philips_gogear_ariaz16gb.png", BrandId=29, ProductGroupId=4},
            new Product { Name="MFC-L2740DW", Image="brother_mfc_l2740dw.png", BrandId=50, ProductGroupId=1},
            new Product { Name="iPod Touch - 4e generatie (32 GB)", Image="apple_ipod_touch___4e_generatie__32_gb_.png", BrandId=24, ProductGroupId=4},
            new Product { Name="DCP-L2500D", Image="brother_dcp_l2500d.png", BrandId=50, ProductGroupId=1},
            new Product { Name="MFC-L8850CDW", Image="brother_mfc_l8850cdw.png", BrandId=50, ProductGroupId=1},
            new Product { Name="MS 312 dn", Image="lexmark_ms_312_dn.png", BrandId=3, ProductGroupId=1},
            new Product { Name="B1265dfw", Image="dell_b1265dfw.png", BrandId=33, ProductGroupId=1},
            new Product { Name="SL-M2825ND", Image="samsung_sl_m2825nd.png", BrandId=30, ProductGroupId=1},
            new Product { Name="SL-M2022W", Image="samsung_sl_m2022w.png", BrandId=30, ProductGroupId=1},
            new Product { Name="Xpress M2022 Mono Laser", Image="samsung_xpress_m2022_mono_laser.png", BrandId=30, ProductGroupId=1},
            new Product { Name="HL-1110E", Image="brother_hl_1110e.png", BrandId=50, ProductGroupId=1},
            new Product { Name="SP 311DN", Image="ricoh_sp_311dn.png", BrandId=41, ProductGroupId=1},
            new Product { Name="C2665dnf", Image="dell_c2665dnf.png", BrandId=33, ProductGroupId=1},
            new Product { Name="B2360d", Image="dell_b2360d.png", BrandId=33, ProductGroupId=1},
            new Product { Name="C2660dn", Image="dell_c2660dn.png", BrandId=33, ProductGroupId=1},
            new Product { Name="HL-L8250CDN", Image="brother_hl_l8250cdn.png", BrandId=50, ProductGroupId=1},
            new Product { Name="HL-L8350CDW", Image="brother_hl_l8350cdw.png", BrandId=50, ProductGroupId=1},
            new Product { Name="SL-C1810W/SEE", Image="samsung_sl_c1810w_see.png", BrandId=30, ProductGroupId=1},
            new Product { Name="SL-M2835DW Mono", Image="samsung_sl_m2835dw_mono.png", BrandId=30, ProductGroupId=1},
            new Product { Name="HL-L9200CDWT", Image="brother_hl_l9200cdwt.png", BrandId=50, ProductGroupId=1},
            new Product { Name="Xpress C1860FW", Image="samsung_xpress_c1860fw.png", BrandId=30, ProductGroupId=1},
            new Product { Name="iPod Touch - 4e generatie (64 GB)", Image="apple_ipod_touch___4e_generatie__64_gb_.png", BrandId=24, ProductGroupId=4},
            new Product { Name="iPod Touch - 4e generatie (16 GB)", Image="apple_ipod_touch___4e_generatie__16_gb_.png", BrandId=24, ProductGroupId=4},
            new Product { Name="iPod Touch - 5e generatie (32 GB) ", Image="apple_ipod_touch___5e_generatie__32_gb__.png", BrandId=24, ProductGroupId=4},
            new Product { Name="DIR 880 L", Image="d_link_dir_880_l.png", BrandId=20, ProductGroupId=7},
            new Product { Name="DIR-890L", Image="d_link_dir_890l.png", BrandId=20, ProductGroupId=7},
            new Product { Name="DSL-3590L", Image="d_link_dsl_3590l.png", BrandId=20, ProductGroupId=7},
            new Product { Name="M5360", Image="tp_link_m5360.png", BrandId=19, ProductGroupId=7},
            new Product { Name="AC750", Image="tp_link_ac750.png", BrandId=19, ProductGroupId=7},
            new Product { Name="TD-W8970B", Image="tp_link_td_w8970b.png", BrandId=19, ProductGroupId=7},
            new Product { Name="ARCHER C9", Image="tp_link_archer_c9.png", BrandId=19, ProductGroupId=7},
            new Product { Name="Archer D7b AC1750", Image="tp_link_archer_d7b_ac1750.png", BrandId=19, ProductGroupId=7},
            new Product { Name="AC 1900 (Touch P5)", Image="tp_link_ac_1900__touch_p5_.png", BrandId=19, ProductGroupId=7},
            new Product { Name="WRT1900AC", Image="linksys_wrt1900ac.png", BrandId=18, ProductGroupId=7},
            new Product { Name="X3500", Image="linksys_x3500.png", BrandId=18, ProductGroupId=7},
            new Product { Name="XAC1200", Image="linksys_xac1200.png", BrandId=18, ProductGroupId=7},
            new Product { Name="WRT1200AC", Image="linksys_wrt1200ac.png", BrandId=18, ProductGroupId=7},
            new Product { Name="EA8500", Image="linksys_ea8500.png", BrandId=18, ProductGroupId=7},
            new Product { Name="WRT1900ACS", Image="linksys_wrt1900acs.png", BrandId=18, ProductGroupId=7},
            new Product { Name="DIR-510L", Image="d_link_dir_510l.png", BrandId=20, ProductGroupId=7},
            new Product { Name="DSL-3580L", Image="d_link_dsl_3580l.png", BrandId=20, ProductGroupId=7},
            new Product { Name="Vigor 2860 ac", Image="draytek_vigor_2860_ac.png", BrandId=21, ProductGroupId=7},
            new Product { Name="Nighthawk X6 R8000", Image="netgear_nighthawk_x6_r8000.png", BrandId=22, ProductGroupId=7},
            new Product { Name="iPod Touch - 5e generatie (64 GB) ", Image="apple_ipod_touch___5e_generatie__64_gb__.png", BrandId=24, ProductGroupId=4},
            new Product { Name="iPod Nano - 7e generatie (16 GB) ", Image="apple_ipod_nano___7e_generatie__16_gb__.png", BrandId=24, ProductGroupId=4},
            new Product { Name="iPod Shuffle - 2012 (2 GB)", Image="apple_ipod_shuffle___2012__2_gb_.png", BrandId=24, ProductGroupId=4},
            new Product { Name="Ipod Touch - 5e generatie (16GB)", Image="apple_ipod_touch___5e_generatie__16gb_.png", BrandId=24, ProductGroupId=4},
            new Product { Name="NWZ-ZX1 ", Image="sony_nwz_zx1_.png", BrandId=31, ProductGroupId=4},
            new Product { Name="NWZ-A15 16GB", Image="sony_nwz_a15_16gb.png", BrandId=31, ProductGroupId=4},
            new Product { Name="Waterbestendige Walkman NWZ-WS613", Image="sony_waterbestendige_walkman_nwz_ws613.png", BrandId=31, ProductGroupId=4},
            new Product { Name="DSL-AC68U", Image="asus_dsl_ac68u.png", BrandId=32, ProductGroupId=7},
            new Product { Name="NW-AH25N", Image="sony_nw_ah25n.png", BrandId=31, ProductGroupId=4},
            new Product { Name="Z1 Intel Core i3", Image="hp_z1_intel_core_i3.png", BrandId=34, ProductGroupId=11},
            new Product { Name="Mac Pro 2014  (Xeon E5) ", Image="apple_mac_pro_2014___xeon_e5__.png", BrandId=24, ProductGroupId=11},
            new Product { Name="BR-6208AC", Image="edimax_br_6208ac.png", BrandId=23, ProductGroupId=7},
            new Product { Name="D6200", Image="netgear_d6200.png", BrandId=22, ProductGroupId=7},
            new Product { Name="AC1900", Image="netgear_ac1900.png", BrandId=22, ProductGroupId=7},
            new Product { Name="R6100 Dual Band", Image="netgear_r6100_dual_band.png", BrandId=22, ProductGroupId=7},
            new Product { Name="R7500 Nighthawk dual band gigabit smart wifi router X4 AC2350", Image="netgear_r7500_nighthawk_dual_band_gigabit_smart_wifi_router_x4_ac2350.png", BrandId=22, ProductGroupId=7},
            new Product { Name="NW-ZX100 128GB", Image="sony_nw_zx100_128gb.png", BrandId=31, ProductGroupId=4},
            new Product { Name="W1070+W", Image="benq_w1070_w.png", BrandId=42, ProductGroupId=5},
            new Product { Name="EH-TW6600", Image="epson_eh_tw6600.png", BrandId=49, ProductGroupId=5},
            new Product { Name="TH682ST", Image="benq_th682st.png", BrandId=42, ProductGroupId=5},
            new Product { Name="SH-2", Image="olympus_sh_2.png", BrandId=45, ProductGroupId=6},
            new Product { Name="Stylus SH-2", Image="olympus_stylus_sh_2.png", BrandId=45, ProductGroupId=6},
            new Product { Name="Tough TG-4", Image="olympus_tough_tg_4.png", BrandId=45, ProductGroupId=6},
            new Product { Name="Stylus 1S", Image="olympus_stylus_1s.png", BrandId=45, ProductGroupId=6},
            new Product { Name="DP3 Quattro", Image="sigma_dp3_quattro.png", BrandId=44, ProductGroupId=6},
            new Product { Name="DP0 Quattro", Image="sigma_dp0_quattro.png", BrandId=44, ProductGroupId=6},
            new Product { Name="IXUS 275 HS", Image="canon_ixus_275_hs.png", BrandId=43, ProductGroupId=6},
            new Product { Name="PowerShot G3 X", Image="canon_powershot_g3_x.png", BrandId=43, ProductGroupId=6},
            new Product { Name="Powershot G5X", Image="canon_powershot_g5x.png", BrandId=43, ProductGroupId=6},
            new Product { Name="PowerShot G9 X", Image="canon_powershot_g9_x.png", BrandId=43, ProductGroupId=6},
            new Product { Name="Cyber-shot HX90V", Image="sony_cyber_shot_hx90v.png", BrandId=31, ProductGroupId=6},
            new Product { Name="CyberShot DSC-HX90", Image="sony_cybershot_dsc_hx90.png", BrandId=31, ProductGroupId=6},
            new Product { Name="Cybershot DSC-RX10 II", Image="sony_cybershot_dsc_rx10_ii.png", BrandId=31, ProductGroupId=6},
            new Product { Name="CyberShot DSC-RX100 IV", Image="sony_cybershot_dsc_rx100_iv.png", BrandId=31, ProductGroupId=6},
            new Product { Name="Cyber-Shot RX1R II", Image="sony_cyber_shot_rx1r_ii.png", BrandId=31, ProductGroupId=6},
            new Product { Name="Q (Typ 116)", Image="leica_q__typ_116_.png", BrandId=53, ProductGroupId=6},
            new Product { Name="GR II", Image="ricoh_gr_ii.png", BrandId=41, ProductGroupId=6},
            new Product { Name="Coolpix S33", Image="nikon_coolpix_s33.png", BrandId=47, ProductGroupId=6},
            new Product { Name="Coolpix L840", Image="nikon_coolpix_l840.png", BrandId=47, ProductGroupId=6},
            new Product { Name="ADS-2100", Image="brother_ads_2100.png", BrandId=50, ProductGroupId=9},
            new Product { Name="ADS-1100W", Image="brother_ads_1100w.png", BrandId=50, ProductGroupId=9},
            new Product { Name="ADS-2100E", Image="brother_ads_2100e.png", BrandId=50, ProductGroupId=9},
            new Product { Name="ADS-2600 WE", Image="brother_ads_2600_we.png", BrandId=50, ProductGroupId=9},
            new Product { Name="ScanMate i940", Image="kodak_scanmate_i940.png", BrandId=48, ProductGroupId=9},
            new Product { Name="i2900", Image="kodak_i2900.png", BrandId=48, ProductGroupId=9},
            new Product { Name="ScanMate i1150", Image="kodak_scanmate_i1150.png", BrandId=48, ProductGroupId=9},
            new Product { Name="Scanstation 710", Image="kodak_scanstation_710.png", BrandId=48, ProductGroupId=9},
            new Product { Name="Scanjet G3110 (L2698A)", Image="hp_scanjet_g3110__l2698a_.png", BrandId=34, ProductGroupId=9},
            new Product { Name="Scanjet 300", Image="hp_scanjet_300.png", BrandId=34, ProductGroupId=9},
            new Product { Name="CanoScan 9000F Mark II", Image="canon_canoscan_9000f_mark_ii.png", BrandId=43, ProductGroupId=9},
            new Product { Name="CanoScan Lide 220", Image="canon_canoscan_lide_220.png", BrandId=43, ProductGroupId=9},
            new Product { Name="DR-F120", Image="canon_dr_f120.png", BrandId=43, ProductGroupId=9},
            new Product { Name="DR C130", Image="canon_dr_c130.png", BrandId=43, ProductGroupId=9},
            new Product { Name="Coolpix L340", Image="nikon_coolpix_l340.png", BrandId=47, ProductGroupId=6},
            new Product { Name="Coolpix P900", Image="nikon_coolpix_p900.png", BrandId=47, ProductGroupId=6},
            new Product { Name="Theta S", Image="ricoh_theta_s.png", BrandId=41, ProductGroupId=6},
            new Product { Name="Snap Instant", Image="polaroid_snap_instant.png", BrandId=40, ProductGroupId=6},
            new Product { Name="Lumix DMC-FT30", Image="panasonic_lumix_dmc_ft30.png", BrandId=39, ProductGroupId=6},
            new Product { Name="ProBook 470 G3 (Core i7)", Image="hp_probook_470_g3__core_i7_.png", BrandId=34, ProductGroupId=2},
            new Product { Name="EliteBook 745 G3 (AMD 10)", Image="hp_elitebook_745_g3__amd_10_.png", BrandId=34, ProductGroupId=2},
            new Product { Name="Chromebook 13 2015 (Celeron)", Image="dell_chromebook_13_2015__celeron_.png", BrandId=33, ProductGroupId=2},
            new Product { Name="Latitude E5250 (Core i5)", Image="dell_latitude_e5250__core_i5_.png", BrandId=33, ProductGroupId=2},
            new Product { Name="Chromebook 13 2015 (Core i5)", Image="dell_chromebook_13_2015__core_i5_.png", BrandId=33, ProductGroupId=2},
            new Product { Name="PRO P ESSENTIAL P2520LA (Core i5)", Image="asus_pro_p_essential_p2520la__core_i5_.png", BrandId=32, ProductGroupId=2},
            new Product { Name="ROG G752VY (Core i7)", Image="asus_rog_g752vy__core_i7_.png", BrandId=32, ProductGroupId=2},
            new Product { Name="ZenBook Pro UX501 (Core i7)", Image="asus_zenbook_pro_ux501__core_i7_.png", BrandId=32, ProductGroupId=2},
            new Product { Name="IdeaPad G50-80 (Core i5)", Image="lenovo_ideapad_g50_80__core_i5_.png", BrandId=1, ProductGroupId=2},
            new Product { Name="Ideapad 100S 11 (Atom)", Image="lenovo_ideapad_100s_11__atom_.png", BrandId=1, ProductGroupId=2},
            new Product { Name="Yoga 900-13 (Core i7)", Image="lenovo_yoga_900_13__core_i7_.png", BrandId=1, ProductGroupId=2},
            new Product { Name="Yoga 700-14 (Core i5)", Image="lenovo_yoga_700_14__core_i5_.png", BrandId=1, ProductGroupId=2},
            new Product { Name="Gaming Notebook IdeaPad Y700  (Core i7)", Image="lenovo_gaming_notebook_ideapad_y700___core_i7_.png", BrandId=1, ProductGroupId=2},
            new Product { Name="Yoga 700-14 (Core i7)", Image="lenovo_yoga_700_14__core_i7_.png", BrandId=1, ProductGroupId=2},
            new Product { Name="IdeaPad 100-15 (Core i3)", Image="lenovo_ideapad_100_15__core_i3_.png", BrandId=1, ProductGroupId=2},
            new Product { Name="Spectre x2 (Core M)", Image="hp_spectre_x2__core_m_.png", BrandId=34, ProductGroupId=2},
            new Product { Name="ProBook 450 G3 (Core i5)", Image="hp_probook_450_g3__core_i5_.png", BrandId=34, ProductGroupId=2},
            new Product { Name="ProBook 430 G3 (Core i5)", Image="hp_probook_430_g3__core_i5_.png", BrandId=34, ProductGroupId=2},
            new Product { Name="Envy 13 (Core i5)", Image="hp_envy_13__core_i5_.png", BrandId=34, ProductGroupId=2},
            new Product { Name="Lumix DMC-TZ57", Image="panasonic_lumix_dmc_tz57.png", BrandId=39, ProductGroupId=6},
            new Product { Name="Lumix DMC-TZ58", Image="panasonic_lumix_dmc_tz58.png", BrandId=39, ProductGroupId=6},
            new Product { Name="Lumix DMC-CM1 EG-S", Image="panasonic_lumix_dmc_cm1_eg_s.png", BrandId=39, ProductGroupId=6},
            new Product { Name="Lumix DMC-FZ300", Image="panasonic_lumix_dmc_fz300.png", BrandId=39, ProductGroupId=6},
            new Product { Name="DMC-TZ80", Image="panasonic_dmc_tz80.png", BrandId=39, ProductGroupId=6},
            new Product { Name="Lumix DMC-TZ100", Image="panasonic_lumix_dmc_tz100.png", BrandId=39, ProductGroupId=6},
            new Product { Name="Surface Pro 4 (Core M)", Image="", BrandId=38, ProductGroupId=2},
            new Product { Name="eScan A 150", Image="plustek_escan_a_150.png", BrandId=51, ProductGroupId=9},
            new Product { Name="Aspire E5-473 (Core i5)", Image="acer_aspire_e5_473__core_i5_.png", BrandId=37, ProductGroupId=2},
            new Product { Name="Aspire VN7-572G (Core i5)", Image="acer_aspire_vn7_572g__core_i5_.png", BrandId=37, ProductGroupId=2},
            new Product { Name="Aspire V 15 Nitro VN7-572G (Core i7)", Image="acer_aspire_v_15_nitro_vn7_572g__core_i7_.png", BrandId=37, ProductGroupId=2},
            new Product { Name="Aspire R5-471T (Core i7)", Image="acer_aspire_r5_471t__core_i7_.png", BrandId=37, ProductGroupId=2},
            new Product { Name="Extensa 2519 (Celeron)", Image="acer_extensa_2519__celeron_.png", BrandId=37, ProductGroupId=2},
            new Product { Name="Gaming GT72S 6QE(Dominator Pro G) Core i7", Image="msi_gaming_gt72s_6qe_dominator_pro_g__core_i7.png", BrandId=36, ProductGroupId=2},
            new Product { Name="Gaming GS40 6QE(Phantom) Core i7", Image="msi_gaming_gs40_6qe_phantom__core_i7.png", BrandId=36, ProductGroupId=2},
            new Product { Name="Satellite L50D-C (AMD A10)", Image="toshiba_satellite_l50d_c__amd_a10_.png", BrandId=35, ProductGroupId=2},
            new Product { Name="Aspire VN7-792G (Core i7)", Image="acer_aspire_vn7_792g__core_i7_.png", BrandId=37, ProductGroupId=2},
            new Product { Name="OpticPro ST640 ", Image="plustek_opticpro_st640_.png", BrandId=51, ProductGroupId=9},
            new Product { Name="OpticBook 3800 ", Image="plustek_opticbook_3800_.png", BrandId=51, ProductGroupId=9},
            new Product { Name="OpticBook 4800", Image="plustek_opticbook_4800.png", BrandId=51, ProductGroupId=9},
            new Product { Name="ProLite XUB2390HS-B1", Image="iiyama_prolite_xub2390hs_b1.png", BrandId=2, ProductGroupId=12},
            new Product { Name="ProLite B2783QSU-B1", Image="iiyama_prolite_b2783qsu_b1.png", BrandId=2, ProductGroupId=12},
            new Product { Name="29UB55-B", Image="lg_29ub55_b.png", BrandId=14, ProductGroupId=12},
            new Product { Name="31MU97-B", Image="lg_31mu97_b.png", BrandId=14, ProductGroupId=12},
            new Product { Name="34UM67-P - Ultra Wide IPS Monitor", Image="lg_34um67_p___ultra_wide_ips_monitor.png", BrandId=14, ProductGroupId=12},
            new Product { Name="27MU67-B", Image="lg_27mu67_b.png", BrandId=14, ProductGroupId=12},
            new Product { Name="Brilliance BDM3470UP", Image="philips_brilliance_bdm3470up.png", BrandId=29, ProductGroupId=12},
            new Product { Name="272S4LPJCB", Image="philips_272s4lpjcb.png", BrandId=29, ProductGroupId=12},
            new Product { Name="275C5QHAW", Image="philips_275c5qhaw.png", BrandId=29, ProductGroupId=12},
            new Product { Name="BDM3270QP", Image="philips_bdm3270qp.png", BrandId=29, ProductGroupId=12},
            new Product { Name="BDM3275UP", Image="philips_bdm3275up.png", BrandId=29, ProductGroupId=12},
            new Product { Name="258B6QJEB", Image="philips_258b6qjeb.png", BrandId=29, ProductGroupId=12},
            new Product { Name="BL3201PH", Image="benq_bl3201ph.png", BrandId=42, ProductGroupId=12},
            new Product { Name="RL2755HM", Image="benq_rl2755hm.png", BrandId=42, ProductGroupId=12},
            new Product { Name="EW2750ZL", Image="benq_ew2750zl.png", BrandId=42, ProductGroupId=12},
            new Product { Name="ProLite B2483HSU-B1DP", Image="iiyama_prolite_b2483hsu_b1dp.png", BrandId=2, ProductGroupId=12},
            new Product { Name="U32E850R", Image="samsung_u32e850r.png", BrandId=30, ProductGroupId=12},
            new Product { Name="S34E790C", Image="samsung_s34e790c.png", BrandId=30, ProductGroupId=12},
            new Product { Name="Q2577PWQ", Image="aoc_q2577pwq.png", BrandId=4, ProductGroupId=12},
            new Product { Name="EH TW 570", Image="epson_eh_tw_570.png", BrandId=49, ProductGroupId=5},
            new Product { Name="EH TW 6600 W", Image="epson_eh_tw_6600_w.png", BrandId=49, ProductGroupId=5},
            new Product { Name="PicoPix PPX3614", Image="philips_picopix_ppx3614.png", BrandId=29, ProductGroupId=5},
            new Product { Name="W1350", Image="benq_w1350.png", BrandId=42, ProductGroupId=5},
            new Product { Name="PH300", Image="lg_ph300.png", BrandId=14, ProductGroupId=5},
            new Product { Name="PF1500G", Image="lg_pf1500g.png", BrandId=14, ProductGroupId=5},
            new Product { Name="PW800G", Image="lg_pw800g.png", BrandId=14, ProductGroupId=5},
            new Product { Name="BL2205PT", Image="benq_bl2205pt.png", BrandId=42, ProductGroupId=12},
            new Product { Name="HDP1690TV", Image="philips_hdp1690tv.png", BrandId=29, ProductGroupId=5},
            new Product { Name="EB-U04", Image="epson_eb_u04.png", BrandId=49, ProductGroupId=5},
            new Product { Name="EH-TW5300", Image="epson_eh_tw5300.png", BrandId=49, ProductGroupId=5},
            new Product { Name="W1110 Full HD", Image="benq_w1110_full_hd.png", BrandId=42, ProductGroupId=5},
            new Product { Name="W2000", Image="benq_w2000.png", BrandId=42, ProductGroupId=5},
            new Product { Name="VPL-VW520 ES", Image="sony_vpl_vw520_es.png", BrandId=31, ProductGroupId=5},
            new Product { Name="W3000", Image="benq_w3000.png", BrandId=42, ProductGroupId=5},
            new Product { Name="Q2778VQE", Image="aoc_q2778vqe.png", BrandId=4, ProductGroupId=12},
            new Product { Name="PicoPix 4010", Image="philips_picopix_4010.png", BrandId=29, ProductGroupId=5},
            new Product { Name="Ecosys P6021CDN", Image="kyocera_ecosys_p6021cdn.png", BrandId=46, ProductGroupId=1},
            new Product { Name="GW2870H", Image="benq_gw2870h.png", BrandId=42, ProductGroupId=12},
            new Product { Name="GW2270H", Image="benq_gw2270h.png", BrandId=42, ProductGroupId=12},
            new Product { Name="Officejet 6230", Image="hp_officejet_6230.png", BrandId=34, ProductGroupId=3},
            new Product { Name="WorkForce Pro WF-5190DW", Image="epson_workforce_pro_wf_5190dw.png", BrandId=49, ProductGroupId=3},
            new Product { Name="DeskJet 2130", Image="hp_deskjet_2130.png", BrandId=34, ProductGroupId=3},
            new Product { Name="Perfection V37", Image="epson_perfection_v37.png", BrandId=49, ProductGroupId=9},
            new Product { Name="DocuMate 5460", Image="xerox_documate_5460.png", BrandId=55, ProductGroupId=9},
            new Product { Name="ScanSnap S1100", Image="fujitsu_scansnap_s1100.png", BrandId=54, ProductGroupId=9},
            new Product { Name="Fi-6140Z", Image="", BrandId=54, ProductGroupId=9},
            new Product { Name="ScanSnap S1300i", Image="fujitsu_scansnap_s1300i.png", BrandId=54, ProductGroupId=9},
            new Product { Name="ScanSnap ix500", Image="fujitsu_scansnap_ix500.png", BrandId=54, ProductGroupId=9},
            new Product { Name="ScanSnap SV600", Image="fujitsu_scansnap_sv600.png", BrandId=54, ProductGroupId=9},
            new Product { Name="Fi-7180", Image="fujitsu_fi_7180.png", BrandId=54, ProductGroupId=9},
            new Product { Name="ScanSnap iX100", Image="fujitsu_scansnap_ix100.png", BrandId=54, ProductGroupId=9},
            new Product { Name="ImageBox LCD9 ", Image="reflecta_imagebox_lcd9_.png", BrandId=52, ProductGroupId=9},
            new Product { Name="MF 5000", Image="reflecta_mf_5000.png", BrandId=52, ProductGroupId=9},
            new Product { Name="Refl RPS 10M 65910", Image="reflecta_refl_rps_10m_65910.png", BrandId=52, ProductGroupId=9},
            new Product { Name="MAXIFY iB4050", Image="canon_maxify_ib4050.png", BrandId=43, ProductGroupId=3},
            new Product { Name="WorkForce Pro WF-5110DW", Image="epson_workforce_pro_wf_5110dw.png", BrandId=49, ProductGroupId=3},
            new Product { Name="Workforce WF-100W", Image="epson_workforce_wf_100w.png", BrandId=49, ProductGroupId=3},
            new Product { Name="Expression Photo XP 55-5760", Image="epson_expression_photo_xp_55_5760.png", BrandId=49, ProductGroupId=3},
            new Product { Name="PA328Q", Image="asus_pa328q.png", BrandId=32, ProductGroupId=12},
            new Product { Name="PB 279 Q", Image="asus_pb_279_q.png", BrandId=32, ProductGroupId=12},
            new Product { Name="ENVY 32", Image="hp_envy_32.png", BrandId=34, ProductGroupId=12},
            new Product { Name="S277hkwmidpp", Image="acer_s277hkwmidpp.png", BrandId=37, ProductGroupId=12},
            new Product { Name="MG 279 Q", Image="asus_mg_279_q.png", BrandId=32, ProductGroupId=12},
            new Product { Name="S Series S2716DG", Image="dell_s_series_s2716dg.png", BrandId=33, ProductGroupId=12},
            new Product { Name="Pixma iP90v", Image="canon_pixma_ip90v.png", BrandId=43, ProductGroupId=3},
            new Product { Name="SW2700PT", Image="benq_sw2700pt.png", BrandId=42, ProductGroupId=12},
            new Product { Name="OfficeJet 100 Mobile Printer", Image="hp_officejet_100_mobile_printer.png", BrandId=34, ProductGroupId=3},
            new Product { Name="Aficio SG 3110DNw", Image="ricoh_aficio_sg_3110dnw.png", BrandId=41, ProductGroupId=3},
            new Product { Name="Pixma Pro-1 ", Image="canon_pixma_pro_1_.png", BrandId=43, ProductGroupId=3},
            new Product { Name="Pixma iP7250", Image="canon_pixma_ip7250.png", BrandId=43, ProductGroupId=3},
            new Product { Name="Workforce WF-3010DW", Image="epson_workforce_wf_3010dw.png", BrandId=49, ProductGroupId=3},
            new Product { Name="Stylus Pro 4900", Image="epson_stylus_pro_4900.png", BrandId=49, ProductGroupId=3},
            new Product { Name="7110 Wide Format ePrinter", Image="hp_7110_wide_format_eprinter.png", BrandId=34, ProductGroupId=3},
            new Product { Name="WorkForce WF-7110DTW", Image="epson_workforce_wf_7110dtw.png", BrandId=49, ProductGroupId=3},
            new Product { Name="Officejet Pro 8100 ePrinter", Image="hp_officejet_pro_8100_eprinter.png", BrandId=34, ProductGroupId=3},
            new Product { Name="FS-2100DN", Image="kyocera_fs_2100dn.png", BrandId=46, ProductGroupId=1}
        };
    private static List<Brand> Brands => new List<Brand>{
            new Brand { Name="Lenovo"},
            new Brand { Name="Iiyama"},
            new Brand { Name="Lexmark"},
            new Brand { Name="AOC"},
            new Brand { Name="Optoma"},
            new Brand { Name="vivitek"},
            new Brand { Name="ViewSonic"},
            new Brand { Name="Pentax"},
            new Brand { Name="Grundig"},
            new Brand { Name="AEG"},
            new Brand { Name="Gigaset"},
            new Brand { Name="Audioline"},
            new Brand { Name="AVM"},
            new Brand { Name="LG"},
            new Brand { Name="Swissvoice"},
            new Brand { Name="Topcom"},
            new Brand { Name="Synology"},
            new Brand { Name="Linksys"},
            new Brand { Name="TP-Link"},
            new Brand { Name="D-link"},
            new Brand { Name="DrayTek"},
            new Brand { Name="Netgear"},
            new Brand { Name="Edimax"},
            new Brand { Name="Apple"},
            new Brand { Name="Cowon"},
            new Brand { Name="Sandisk"},
            new Brand { Name="Archos"},
            new Brand { Name="Siemens"},
            new Brand { Name="Philips"},
            new Brand { Name="Samsung"},
            new Brand { Name="Sony"},
            new Brand { Name="Asus"},
            new Brand { Name="Dell"},
            new Brand { Name="HP"},
            new Brand { Name="Toshiba"},
            new Brand { Name="MSI"},
            new Brand { Name="Acer"},
            new Brand { Name="Microsoft"},
            new Brand { Name="Panasonic"},
            new Brand { Name="Polaroid"},
            new Brand { Name="Ricoh"},
            new Brand { Name="BenQ"},
            new Brand { Name="Canon"},
            new Brand { Name="Sigma"},
            new Brand { Name="Olympus"},
            new Brand { Name="Kyocera"},
            new Brand { Name="Nikon"},
            new Brand { Name="Kodak"},
            new Brand { Name="Epson"},
            new Brand { Name="Brother"},
            new Brand { Name="Plustek"},
            new Brand { Name="Reflecta"},
            new Brand { Name="Leica"},
            new Brand { Name="Fujitsu"},
            new Brand { Name="Xerox"}
        };
    private static List<Review> Reviews => new List<Review>{
        new Review {Author = "Naam 1", Email = "naam1@review.zp", Score = 5, ProductId=1, Text="Lorum 1"},
        new Review {Author = "Naam 2", Email = "naam2@review.zp", Score = 5, ProductId=1, Text="Lorum 2"},
        new Review {Author = "Naam 3", Email = "naam3@review.zp", Score = 4, ProductId=1, Text="Lorum 3"},
        new Review {Author = "Naam 4", Email = "naam4@review.zp", Score = 3, ProductId=1, Text="Lorum 4"},
        new Review {Author = "Naam 5", Email = "naam5@review.zp", Score = 2, ProductId=1, Text="Lorum 5"},
        new Review {Author = "Naam 6", Email = "naam6@review.zp", Score = 1, ProductId=1, Text="Lorum 6"},
        new Review {Author = "Naam 7", Email = "naam7@review.zp", Score = 2, ProductId=1, Text="Lorum 7"},
        new Review {Author = "Naam 8", Email = "naam8@review.zp", Score = 3, ProductId=1, Text="Lorum 8"},
        new Review {Author = "Naam 9", Email = "naam9@review.zp", Score = 4, ProductId=1, Text="Lorum 9"},
        new Review {Author = "Naam 10", Email = "naam10@review.zp", Score = 5, ProductId=1, Text="Lorum 10"}
    };
}